### ISSUE TITLE
Suchtimer view is empty

### ISSUE THREAD

**Issue by NemoN** [Zabrimus/vdr-jonglisto#2]
I have some Suchtimer, but the view is empty, should it work already?

<img width="680" alt="bildschirmfoto 2016-12-21 um 17 23 29" src="https://cloud.githubusercontent.com/assets/2212175/21396965/48fb4056-c7a2-11e6-8fa8-21f26084a128.png">

**Comment by Zabrimus** [comment]
Empty? I would expect all currently defined search timers found in the epg2vdr database.
Or are you expecting epgsearch timers? This part is currently not yet implemented.

**Comment by NemoN** [comment]
The timers from the epg2vdr database are shown (Timer). 
The epgsearch timers (Suchtimer) not...
